name: Android

on:
  push:
    paths:
      - 'android/**'
      - '.github/workflows/android.yaml'
  workflow_dispatch:

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Smoke test
        run: echo hello
